global:
  scrape_interval:     10s
  evaluation_interval: 10s

  external_labels:
    monitor: 'prometheus'

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'

    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9100']
        labels:
          group: 'local'
          instance: 'playground'
